@ProductApp.API_HostAddress = https://localhost:7299
@id=14

GET {{ProductApp.API_HostAddress}}/api/color/{{id}}

###

POST {{ProductApp.API_HostAddress}}/api/color
Content-Type: application/json

{
    "name": "Amarillo"
}

###

PUT {{ProductApp.API_HostAddress}}/api/color
Content-Type: application/json

{
  "id": 1,
  "name": "Rojo"
}

###

DELETE {{ProductApp.API_HostAddress}}/api/color/{{id}}

###










GET {{ProductApp.API_HostAddress}}/api/product/{{id}}

###


POST {{ProductApp.API_HostAddress}}/api/product
Content-Type: application/json

{
  "name": "TV",
  "productPrices": [
      {
          "id": 27,
          "price": 7,
          "isSelected": true,
          "productId": 0,
          "colorId": 3
      },
      {
          "id": 28,
          "price": 88,
          "isSelected": false,
          "productId": 0,
          "colorId": 3
      },
      {
          "id": 29,
          "price": 99,
          "isSelected": false,
          "productId": 0,
          "colorId": 2
      }
  ]
}

###

DELETE {{ProductApp.API_HostAddress}}/api/product/{{id}}

###

GET {{ProductApp.API_HostAddress}}/api/product

###

PUT {{ProductApp.API_HostAddress}}/api/product
Content-Type: application/json

{
  "id": 14,
  "name": "iPhone",
  "productPrices": [
      {
          "id": 27,
          "price": 90,
          "isSelected": true,
          "productId": 14,
          "colorId": 2
      },
      {
          "id": 28,
          "price": 120,
          "isSelected": false,
          "productId": 14,
          "colorId": 2
      },
      {
          "id": 29,
          "price": 130,
          "isSelected": false,
          "productId": 14,
          "colorId": 2
      }
  ]
}

###
